import json

translations = {
    "Acid Arrow": "Säurepfeil",
    "Acid Splash": "Säurespritzer",
    "Aid": "Beistand",
    "Alarm": "Alarm",
    "Alter Self": "Gestalt ändern",
    "Animal Friendship": "Tierfreundschaft",
    "Animal Messenger": "Tierbote",
    "Animal Shapes": "Tiergestalten",
    "Animate Dead": "Tote beleben",
    "Animate Objects": "Gegenstände beleben",
    "Antilife Shell": "Antilebenshülle",
    "Antimagic Field": "Antimagisches Feld",
    "Antipathy/Sympathy": "Antipathie/Sympathie",
    "Arcane Eye": "Arkanes Auge",
    "Arcane Hand": "Arkane Hand",
    "Arcane Lock": "Arkanes Schloss",
    "Arcane Sword": "Arkanes Schwert",
    "Arcanist's Magic Aura": "Magische Aura des Arkanisten",
    "Astral Projection": "Astralprojektion",
    "Augury": "Weissagung",
    "Awaken": "Erwecken",
    "Bane": "Verderben",
    "Banishment": "Verbannung",
    "Barkskin": "Rindenhaut",
    "Beacon of Hope": "Leuchtfeuer der Hoffnung",
    "Bestow Curse": "Fluch",
    "Black Tentacles": "Schwarze Tentakel",
    "Blade Barrier": "Klingenschranke",
    "Bless": "Segen",
    "Blight": "Verdorren",
    "Blindness/Deafness": "Blindheit/Taubheit",
    "Blink": "Blinzeln",
    "Blur": "Verschwimmen",
    "Branding Smite": "Zeichen des Richtens",
    "Burning Hands": "Brennende Hände",
    "Call Lightning": "Blitz herbeirufen",
    "Calm Emotions": "Gefühle besänftigen",
    "Chain Lightning": "Kettenblitz",
    "Charm Person": "Person bezaubern",
    "Chill Touch": "Berührung des Frosts",
    "Circle of Death": "Kreis des Todes",
    "Clairvoyance": "Hellsehen",
    "Clone": "Klonen",
    "Cloudkill": "Tödliche Wolke",
    "Color Spray": "Farbenstrahl",
    "Command": "Befehl",
    "Commune": "Kommunion",
    "Commune With Nature": "Eins mit der Natur",
    "Comprehend Languages": "Sprachen verstehen",
    "Compulsion": "Zwang",
    "Cone of Cold": "Kältekegel",
    "Confusion": "Verwirrung",
    "Conjure Animals": "Tiere herbeizaubern",
    "Conjure Celestial": "Himmlische herbeizaubern",
    "Conjure Elemental": "Elementar herbeizaubern",
    "Conjure Fey": "Fee herbeizaubern",
    "Conjure Minor Elementals": "Niedere Elementare herbeizaubern",
    "Conjure Woodland Beings": "Waldwesen herbeizaubern",
    "Contact Other Plane": "Andere Ebene kontaktieren",
    "Contagion": "Ansteckung",
    "Contingency": "Kontingenz",
    "Continual Flame": "Ewige Flamme",
    "Control Water": "Wasser kontrollieren",
    "Control Weather": "Wetterkontrolle",
    "Counterspell": "Gegenzauber",
    "Create Food and Water": "Nahrung und Wasser erschaffen",
    "Create or Destroy Water": "Wasser erschaffen oder vernichten",
    "Create Undead": "Untote erschaffen",
    "Creation": "Erschaffung",
    "Cure Wounds": "Wunden heilen",
    "Dancing Lights": "Tanzende Lichter",
    "Darkness": "Dunkelheit",
    "Darkvision": "Dunkelsicht",
    "Daylight": "Tageslicht",
    "Death Ward": "Todesschutz",
    "Delayed Blast Fireball": "Verzögerter Feuerball",
    "Demiplane": "Halbebene",
    "Detect Evil and Good": "Böses und Gutes entdecken",
    "Detect Magic": "Magie entdecken",
    "Detect Poison and Disease": "Gift und Krankheit entdecken",
    "Detect Thoughts": "Gedankenlesen",
    "Dimension Door": "Dimensionstor",
    "Disguise Self": "Selbstverkleidung",
    "Disintegrate": "Auflösen",
    "Dispel Evil and Good": "Böses und Gutes bannen",
    "Dispel Magic": "Magie bannen",
    "Divination": "Erkenntnismagie",
    "Divine Favor": "Göttliche Gunst",
    "Divine Word": "Göttliches Wort",
    "Dominate Beast": "Tier beherrschen",
    "Dominate Monster": "Monster beherrschen",
    "Dominate Person": "Person beherrschen",
    "Dream": "Traum",
    "Druidcraft": "Druidenzauber",
    "Earthquake": "Erdbeben",
    "Eldritch Blast": "Schauriger Strahl",
    "Enhance Ability": "Fähigkeit verbessern",
    "Enlarge/Reduce": "Vergrößern/Verkleinern",
    "Entangle": "Verstricken",
    "Enthrall": "Fesseln",
    "Etherealness": "Ätherischsein",
    "Expeditious Retreat": "Beschleunigter Rückzug",
    "Eyebite": "Augenbiss",
    "Fabricate": "Herstellen",
    "Faerie Fire": "Feenfeuer",
    "Faithful Hound": "Treuer Hund",
    "False Life": "Falsches Leben",
    "Fear": "Furcht",
    "Feather Fall": "Federfall",
    "Feeblemind": "Schwachsinn",
    "Find Familiar": "Vertrauten finden",
    "Find Steed": "Ross finden",
    "Find the Path": "Weg finden",
    "Find Traps": "Fallen finden",
    "Finger of Death": "Finger des Todes",
    "Fire Bolt": "Feuerpfeil",
    "Fire Shield": "Feuerschild",
    "Fire Storm": "Feuersturm",
    "Fireball": "Feuerball",
    "Flame Blade": "Flammenklinge",
    "Flame Strike": "Flammenschlag",
    "Flaming Sphere": "Flammende Kugel",
    "Flesh to Stone": "Fleisch zu Stein",
    "Floating Disk": "Schwebende Scheibe",
    "Fly": "Fliegen",
    "Fog Cloud": "Nebelwolke",
    "Forbiddance": "Verbot",
    "Forcecage": "Kraftkäfig",
    "Foresight": "Voraussicht",
    "Freedom of Movement": "Bewegungsfreiheit",
    "Freezing Sphere": "Eiskugel",
    "Gaseous Form": "Gasförmige Gestalt",
    "Gate": "Tor",
    "Geas": "Geas",
    "Gentle Repose": "Sanfte Ruhe",
    "Giant Insect": "Riesiges Insekt",
    "Glibness": "Wortgewandtheit",
    "Globe of Invulnerability": "Kugel der Unverwundbarkeit",
    "Glyph of Warding": "Schutzglyphe",
    "Goodberry": "Gute Beere",
    "Grease": "Fett",
    "Greater Invisibility": "Mächtige Unsichtbarkeit",
    "Greater Restoration": "Mächtige Wiederherstellung",
    "Guardian of Faith": "Glaubenswächter",
    "Guards and Wards": "Wachen und Schutzzauber",
    "Guidance": "Führung",
    "Guiding Bolt": "Leitender Blitz",
    "Gust of Wind": "Windstoß",
    "Hallow": "Weihen",
    "Hallucinatory Terrain": "Halluzinatorisches Gelände",
    "Harm": "Verletzen",
    "Haste": "Hast",
    "Heal": "Heilung",
    "Healing Word": "Heilendes Wort",
    "Heat Metal": "Metall erhitzen",
    "Hellish Rebuke": "Höllischer Tadel",
    "Heroes' Feast": "Heldenmahl",
    "Heroism": "Heldenmut",
    "Hideous Laughter": "Abscheuliches Lachen",
    "Hold Monster": "Monster festhalten",
    "Hold Person": "Person festhalten",
    "Holy Aura": "Heilige Aura",
    "Hunter's Mark": "Zeichen des Jägers",
    "Hypnotic Pattern": "Hypnotisches Muster",
    "Ice Storm": "Eissturm",
    "Identify": "Identifizieren",
    "Illusory Script": "Illusorische Schrift",
    "Imprisonment": "Einkerkerung",
    "Incendiary Cloud": "Brandwolke",
    "Inflict Wounds": "Wunden verursachen",
    "Insect Plague": "Insektenplage",
    "Instant Summons": "Sofortige Beschwörung",
    "Invisibility": "Unsichtbarkeit",
    "Irresistible Dance": "Unwiderstehlicher Tanz",
    "Jump": "Springen",
    "Knock": "Klopfen",
    "Legend Lore": "Sagenkunde",
    "Lesser Restoration": "Kleine Wiederherstellung",
    "Levitate": "Schweben",
    "Light": "Licht",
    "Lightning Bolt": "Blitz",
    "Locate Animals or Plants": "Tiere oder Pflanzen aufspüren",
    "Locate Creature": "Kreatur aufspüren",
    "Locate Object": "Objekt aufspüren",
    "Longstrider": "Langschritt",
    "Mage Armor": "Magierrüstung",
    "Mage Hand": "Magierhand",
    "Magic Circle": "Magischer Kreis",
    "Magic Jar": "Magisches Gefäß",
    "Magic Missile": "Magisches Geschoss",
    "Magic Mouth": "Magischer Mund",
    "Magic Weapon": "Magische Waffe",
    "Magnificent Mansion": "Prächtiges Herrenhaus",
    "Major Image": "Mächtiges Trugbild",
    "Mass Cure Wounds": "Massen-Wundenheilen",
    "Mass Heal": "Massenheilung",
    "Mass Healing Word": "Massen-Heilendes Wort",
    "Mass Suggestion": "Massen-Suggestion",
    "Maze": "Labyrinth",
    "Meld Into Stone": "Mit Stein verschmelzen",
    "Mending": "Reparieren",
    "Message": "Nachricht",
    "Meteor Swarm": "Meteorschwarm",
    "Mind Blank": "Gedankenleere",
    "Minor Illusion": "Kleine Illusion",
    "Mirage Arcane": "Trugbild",
    "Mirror Image": "Spiegelbild",
    "Mislead": "Irreführung",
    "Misty Step": "Nebelschritt",
    "Modify Memory": "Erinnerung modifizieren",
    "Moonbeam": "Mondstrahl",
    "Move Earth": "Erde bewegen",
    "Nondetection": "Nichtentdeckung",
    "Pass Without Trace": "Spurlos vorübergehen",
    "Passwall": "Wand durchdringen",
    "Phantasmal Killer": "Phantastischer Mörder",
    "Phantom Steed": "Phantomross",
    "Planar Ally": "Planarer Verbündeter",
    "Planar Binding": "Planare Bindung",
    "Plane Shift": "Ebenenwechsel",
    "Plant Growth": "Pflanzenwachstum",
    "Poison Spray": "Giftstrahl",
    "Polymorph": "Verwandlung",
    "Power Word Kill": "Machtwort: Tod",
    "Power Word Stun": "Machtwort: Betäubung",
    "Prayer of Healing": "Gebet der Heilung",
    "Prestidigitation": "Taschenspielerei",
    "Prismatic Spray": "Prismatischer Strahl",
    "Prismatic Wall": "Prismatische Wand",
    "Private Sanctum": "Privates Heiligtum",
    "Produce Flame": "Flamme erzeugen",
    "Programmed Illusion": "Programmierte Illusion",
    "Project Image": "Bild projizieren",
    "Protection From Energy": "Schutz vor Energie",
    "Protection from Evil and Good": "Schutz vor Bösem und Gutem",
    "Protection from Poison": "Schutz vor Gift",
    "Purify Food and Drink": "Nahrung und Getränk reinigen",
    "Raise Dead": "Tote erwecken",
    "Ray of Enfeeblement": "Strahl der Entkräftung",
    "Ray of Frost": "Kältestrahl",
    "Regenerate": "Regenerieren",
    "Reincarnate": "Reinkarnation",
    "Remove Curse": "Fluch brechen",
    "Resilient Sphere": "Elastische Kugel",
    "Resistance": "Resistenz",
    "Resurrection": "Wiederauferstehung",
    "Reverse Gravity": "Schwerkraft umkehren",
    "Revivify": "Wiederbeleben",
    "Rope Trick": "Seiltrick",
    "Sacred Flame": "Heilige Flamme",
    "Sanctuary": "Heiligtum",
    "Scorching Ray": "Sengender Strahl",
    "Scrying": "Ausspähung",
    "Secret Chest": "Geheime Kiste",
    "See Invisibility": "Unsichtbarkeit sehen",
    "Seeming": "Schein",
    "Sending": "Senden",
    "Sequester": "Abschirmen",
    "Shapechange": "Gestaltwandel",
    "Shatter": "Zerschmettern",
    "Shield": "Schild",
    "Shield of Faith": "Schild des Glaubens",
    "Shillelagh": "Shillelagh",
    "Shocking Grasp": "Schockgriff",
    "Silence": "Stille",
    "Silent Image": "Stilles Bild",
    "Simulacrum": "Simulakrum",
    "Sleep": "Schlaf",
    "Sleet Storm": "Graupelsturm",
    "Slow": "Verlangsamen",
    "Spare the Dying": "Die Sterbenden schonen",
    "Speak with Animals": "Mit Tieren sprechen",
    "Speak with Dead": "Mit Toten sprechen",
    "Speak with Plants": "Mit Pflanzen sprechen",
    "Spider Climb": "Spinnenklettern",
    "Spike Growth": "Stachelwuchs",
    "Spirit Guardians": "Geisterwächter",
    "Spiritual Weapon": "Geisterwaffe",
    "Stinking Cloud": "Stinkende Wolke",
    "Stone Shape": "Stein formen",
    "Stoneskin": "Steinhaut",
    "Storm of Vengeance": "Sturm der Vergeltung",
    "Suggestion": "Suggestion",
    "Sunbeam": "Sonnenstrahl",
    "Sunburst": "Sonnenfeuer",
    "Symbol": "Symbol",
    "Telekinesis": "Telekinese",
    "Telepathic Bond": "Telepathische Verbindung",
    "Teleport": "Teleportieren",
    "Teleportation Circle": "Teleportationszirkel",
    "Thaumaturgy": "Thaumaturgie",
    "Thunderwave": "Donnerwelle",
    "Time Stop": "Zeitstopp",
    "Tiny Hut": "Winzige Hütte",
    "Tongues": "Zungen",
    "Transport via Plants": "Transport über Pflanzen",
    "Tree Stride": "Baumschritt",
    "True Polymorph": "Wahre Verwandlung",
    "True Resurrection": "Wahre Wiederauferstehung",
    "True Seeing": "Wahre Sicht",
    "True Strike": "Wahrer Schlag",
    "Unseen Servant": "Unsichtbarer Diener",
    "Vampiric Touch": "Vampirische Berührung",
    "Vicious Mockery": "Böser Spott",
    "Wall of Fire": "Feuerwand",
    "Wall of Force": "Kraftwand",
    "Wall of Ice": "Eiswand",
    "Wall of Stone": "Steinwand",
    "Wall of Thorns": "Dornenwand",
    "Warding Bond": "Schutzbund",
    "Water Breathing": "Wasseratmung",
    "Water Walk": "Wasserwandeln",
    "Web": "Netz",
    "Weird": "Seltsam",
    "Wind Walk": "Windwandeln",
    "Wind Wall": "Windwall",
    "Wish": "Wunsch",
    "Word of Recall": "Wort des Rückrufs",
    "Zone of Truth": "Zone der Wahrheit"
}

with open("data/spells.json", "r", encoding="utf-8") as f:
    spells = json.load(f)

translated_spells = {}
for spell_name, spell_data in spells.items():
    if spell_name in translations:
        translated_spells[translations[spell_name]] = spell_data
    else:
        translated_spells[spell_name] = spell_data

with open("data/spells_translated.json", "w", encoding="utf-8") as f:
    json.dump(translated_spells, f, indent=4, ensure_ascii=False)
