<CharacterCreator>:
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        ScrollView:
            size_hint: 1, 1
            do_scroll_x: False
            do_scroll_y: True
            GridLayout:
                id: creator_layout
                cols: 2
                padding: 10
                spacing: 10
                size_hint_y: None
                height: self.minimum_height
