<MainMenu>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

        Image:
            source: 'logo/logo.png'

        Button:
            text: "Charakter"
            on_press: root.go_to_screen('character_menu')

        Button:
            text: "DM Spiel"
            on_press: root.go_to_screen('dm_spiel')

        Button:
            text: "Optionen"
            on_press: root.go_to_screen('options')
