name: Build Android APK

on:
  push:
    branches: [ "main", "beta", "android-windows-build" ]
  pull_request:
    branches: [ "main", "beta", "android-windows-build" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Cython==0.29.33"
          pip install -r requirements.txt
          pip install buildozer

      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Manually Accept Licenses and Install Build Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo "24333f8a63b6825ea9c5514f83c272964db54815" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-31" "build-tools;29.0.0"

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dndapp-debug
          path: bin/*.apk
