name: Build Android APK

on:
  push:
    branches: [ "main", "beta", "android-windows-build" ]
  pull_request:
    branches: [ "main", "beta", "android-windows-build" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          python -m pip install --upgrade pip
          pip install "Cython==0.29.33"
          pip install -r requirements.txt
          pip install buildozer

      - name: Prepare Buildozer Environment
        run: |
          buildozer android release || true

      - name: Manually Accept Licenses and Install Build Tools
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c272964db54815" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=~/.buildozer/android/platform/android-sdk "build-tools;29.0.0"
          find ~/.buildozer/android/platform/android-sdk/build-tools/ -mindepth 1 -maxdepth 1 ! -name '29.0.0' -exec rm -rf {} +

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dndapp-debug
          path: bin/*.apk
