name: Build Android APK

on:
  push:
    branches: [ "main", "beta", "android-windows-build" ]
  pull_request:
    branches: [ "main", "beta", "android-windows-build" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      
      # NEUER, VERBESSERTER SCHRITT
      - name: Install Android SDK components
        run: |
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" --sdk_root=$ANDROID_SDK_ROOT
          echo "--- Listing installed packages ---"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list_installed
          echo "--- Listing contents of build-tools directory ---"
          ls -la $ANDROID_SDK_ROOT/build-tools/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install buildozer cython

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dndapp-debug
          path: bin/*.apk
