name: Build Raspberry Pi Images for Zero, 3, 4, 5 with Autostart

on:
  workflow_dispatch:

jobs:
  build-pi-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: rpi-zero
            image_url: https://downloads.raspberrypi.org/raspios_lite_armhf_latest
            image_name: rpi-zero.img
          - name: rpi-3-4
            image_url: https://downloads.raspberrypi.org/raspios_lite_arm64_latest
            image_name: rpi-3-4.img
          - name: rpi-5
            image_url: https://downloads.raspberrypi.com/raspios_arm64/images/raspios_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64.img.xz
            image_name: rpi-5.img
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils kpartx

      - name: Download Raspberry Pi OS image
        run: |
          wget -O ${{ matrix.image_name }}.xz ${{ matrix.image_url }}
          xz -d ${{ matrix.image_name }}.xz

      - name: Expand image size and filesystem
        run: |
          set -e
          # Enlarge image by 2G
          qemu-img resize ${{ matrix.image_name }} +2G
          # Attach loop device
          sudo losetup -Pf ${{ matrix.image_name }}
          sudo partprobe /dev/loop0
          # Resize partition 2 to fill image (non-interactive)
          sudo parted --script /dev/loop0 resizepart 2 100%
          sudo partprobe /dev/loop0
          # Map partitions
          sudo kpartx -av ${{ matrix.image_name }}
          sleep 2
          # Run fsck and resize2fs on root partition (non-interactive)
          sudo e2fsck -f -y /dev/mapper/loop0p2 || true
          sudo resize2fs /dev/mapper/loop0p2
          # Cleanup
          sudo kpartx -dv ${{ matrix.image_name }}
          sudo losetup -d /dev/loop0

      - name: Mount image and copy project with autostart
        run: |
          set -e
          sudo losetup -Pf ${{ matrix.image_name }}
          sudo partprobe /dev/loop0
          sudo kpartx -av ${{ matrix.image_name }}
          sleep 2
          if [ ! -e /dev/mapper/loop0p2 ]; then
            echo "Partition /dev/mapper/loop0p2 not found!"
            sudo kpartx -dv ${{ matrix.image_name }}
            sudo losetup -d /dev/loop0
            exit 1
          fi
          MOUNTDIR=$(mktemp -d)
          sudo mount /dev/mapper/loop0p2 $MOUNTDIR
          sudo mkdir -p $MOUNTDIR/home/pi/DnD-Sheet-Book-
          sudo cp -r . $MOUNTDIR/home/pi/DnD-Sheet-Book-
          sudo chown -R 1000:1000 $MOUNTDIR/home/pi/DnD-Sheet-Book-
          sudo tee $MOUNTDIR/home/pi/start_dnd_app.sh > /dev/null <<'EOF'
          #!/bin/bash
          cd /home/pi/DnD-Sheet-Book-
          pip3 install -r requirements.txt
          python3 main.py
          EOF
          sudo chmod +x $MOUNTDIR/home/pi/start_dnd_app.sh
          if ! grep -q start_dnd_app.sh $MOUNTDIR/etc/rc.local; then
            sudo sed -i '/^exit 0/i su - pi -c "/home/pi/start_dnd_app.sh &"' $MOUNTDIR/etc/rc.local
          fi
          sudo umount $MOUNTDIR
          sudo kpartx -dv ${{ matrix.image_name }}
          sudo losetup -d /dev/loop0

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-image-autostart
          path: ${{ matrix.image_name }}
